description: "Nonlagged X-cells config file"

#------------Integrator settings-----------------#
ns: 8
nt: 3
dt: 0.1
ds: 0.05
#------------Stimulus settings-----------------#
# Grating:
C: 1.0
mask: "circle" # none/circle/gauss
maskSize: 0.5
kxId:  0        #[-ns/2, ns/2 - 1]
kyId:  0        #[-ns/2, ns/2 - 1]
wId:   0        #[-nt/2, nt/2 - 1]


#----------Ganglion Impulse response--------------#
ganglionImpRes:
# DOG
    A: 1.0
    a: 0.62
    B: 0.85
    b: 1.26

# TemporallyConstant
    constant: 1.0

#------------spatialKernelSettings-----------------#
spatialKernels:
# DOG
    A: 0.0
    a: 0.1
    B: 0.56
    b: 0.88

# SpatialDelta
    weight: 0.81


#------------temporalKernelSettings-----------------#
temporalKernels:

# TemporallyConstant
    constant: 1.0

#------------File manager settings-----------------#
outputFile: "../../../DATA/tmp/nonlaggedXCells.h5"



























