description: "config file"

#------------File manager settings-----------------#
OutputManager:
    outputFilename: "out.h5"

#------------Integrator settings-----------------#
grid:
    ns: 6
    nt: 5
    dt: &dt_id 1.0
    ds: &ds_id 0.05

#------------Stimulus settings-------------------#
stimulus:
    # Grating:
    mask: "none"  #none/circle/cscircle/gaussian

    C: 1.0
    maskSize: 1         #deg
    orientation: 0.     #deg
    phase: 0.           #deg
    kId:  7             #[-Ns/2, Ns/2 - 1]
    wId:  2             #[-Nt/2, Nt/2 - 1]

#-------------Ganglion cell settings--------------#
ganglion:
    R0 : 0
    w: 1.0
    Wg:
    # DOG
        a: 0.62
        b: 1.26
        c: 0.85
    Wt:
    # TemporalDelta
        delay: 0
        dt: *dt_id

#---------------Relay cell settings--------------#
relay:
    R0 : 0
    #Kernels
    Krg:
        w: 1.0
        spatial:
        # Gaussian
            a: 0.1

        temporal:
        # TemporalDelta
            delay: 0
            dt: *dt_id

    Krc:
        w: 0.5
        spatial:
        #Gauss
            a: 0.2

        temporal:
        # TemporalDelta
            delay: 0.
            dt: *dt_id

#-------------Cortical cell settings--------------#
cortical:
    R0 : 0.
    Kcr:
        w: 1.0
        spatial:
        #Spatial delta
            ds: *ds_id
            shift: [0, 0]

        temporal:
        # TemporalDelta
            delay: 0.
            dt: *dt_id

