description: "Default config file"

#------------Integrator settings-----------------#
ns: 8
nt: 6
dt: 0.1

#------------Stimulus settings-----------------#
# Grating:
C: 1.
mask: "circle" # none/circle/gauss
maskSize: 0.8

# NaturalScene:
sceneFilename: "../../../stimuli/lena.png"

# NaturalSceneVideo:
videoFilename: "../../../stimuli/minions.mp4"


#------------spatialKernelSettings-----------------#
# DOG
A: 1.0
a: 0.1
B: 0.5
b: 0.1

# EllipticGaussian
weight_elliptic: 2.3
angle: -45.0
widthLong: 0.1
widthNarrow: 0.001


#------------temporalKernelSettings-----------------#
# Damped oscillator:
phaseDuration: 0.425
weight: 0.5

# DecayingExponential:
delay: 1.1         #s
tau  : 0.42        #s

# TemporallyConstant:
constant: 1.0



#------------Static nonlinearity settings-----------------#
# Threshold function:
threshold: 0.0
weight: 1.0

# Sigmoidal:
maxValue: 1.
halfMaxValue: 3.0
exponent: 2.0


#------------File manager settings-----------------#
outputFile: ""

