description: "Default config file"

#------------Integrator settings-----------------#
ns: 9
nt: 4
dt: 0.1

#------------Stimulus settings-----------------#
# Grating:
C: 1.0
mask: "circle" # none/circle/gauss
maskSize: 0.5

#------------spatialKernelSettings-----------------#
# DOG
A: 1.0
a: 0.06
B: 0.8
b: 0.12


#------------temporalKernelSettings-----------------#
# Temporal delta:
delay: 0.0 #s


#------------File manager settings-----------------#
outputFile: "../../../DATA/spatialSummation/tmp/spatialSummation.h5"

