description: "Default config file"

#------------Integrator settings-----------------#
ns: 6
nt: 7
dt: &dt_id 0.5
ds: &ds_id 0.05

#------------Stimulus settings-----------------#
# Grating:
C: 1.0
mask: "none" # none/circle
maskSize: 0.5
kxId:  0        #[-Ns/2, Ns/2 - 1]
kyId:  1        #[-Ns/2, Ns/2 - 1]
wId:   3        #[-Nt/2, Nt/2 - 1]

# NaturalSceneVideo:
videoFilename: "../../../stimuli/minions.mp4"
#sceneFilename: "../../../stimuli/dog.png"


#----------Ganglion Impulse response--------------#
ganglionImpRes:
# DOG
    A: 1.0
    a: 0.25
    B: 0.85
    b: 0.83

## Biphasic
    #phaseDuration: 42.5
    #weight: 0.38
    #delay: 60

# SpatialDelta
    weight: 1.0
    ds : *ds_id
    shift: [0., 0.]

# TemporalDelta
    delay: 35.
    dt: *dt_id


#------------spatialKernelSettings-----------------#
spatialKernels:
    Krg:
    # SpatialDelta
        weight: 1.0
        ds : *ds_id
        shift: [0.0, 0.]

    Krc:
    # Gauss
        A: -1.5
        a: 0.83

    Kcr:
    # SpatialDelta
        weight: 1.0
        ds : *ds_id
        shift: [0., 0.]

#------------temporalKernelSettings-----------------#
temporalKernels:
    Krg:
    # DoE
        cenLatency: 16
        surLatency: 32
        delay: 200

    Kcr:
     #DoE
        delay: 200.
        dt: *dt_id

    Krc:
     #DoE
         cenLatency: 16
         surLatency: 32
         delay: 200.


#------------backgroundResponse-----------------#
backgroundResponse:
    Rg_0: 0
    Rr_0: 0
    Rc_0: 0

#------------File manager settings-----------------#
outputFile: "/media/milad/scratch/lgn-simulator/simulations/tmp/default.h5"
